{
 "title": "RecsysMonitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(recsys_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(recsys_latency_seconds_sum[1m]) / rate(recsys_latency_seconds_count[1m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "recsys_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}